### PR TITLE
Shorten notebook container name

### PR DESCRIPTION
**Pull request by athornton**

### CODE REVIEW

**Comment by cbanek** [comment]
I'm a bit nervous only because I think this may get confusing in argocd, since the nublado-users overlaps namespaces and doesn't show the namespaces I think on the UI?  Can you try out this change and see how argocd looks and if it is still usable?

**Comment by cbanek** [comment]
I'd also be fine with nb-username

**Review by cbanek — APPROVED** [review]
Looks fine from a code pov, just the question about argocd and how it looks before we merge, since we've been trying to make that useful

**Comment by athornton** [comment]
Crap, you're right.  The only obvious way to tell the users apart with the default argocd visibility settings is the pod name.

**Pull request merged**
